services:
  api:
    image: hashicorp/http-echo:1.0.0
    command: ["-text=lab-api", "-listen=:8080"]
    ports:
      - "18080:8080"
    labels:
      nexus.project: "lab"
      nexus.service: "api"
  web:
    image: nginx:alpine
    ports:
      - "18081:80"
    labels:
      nexus.project: "lab"
      nexus.service: "web"
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
      POSTGRES_DB: lab
    ports:
      - "15432:5432"
    labels:
      nexus.project: lab
      nexus.service: db
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: lab
      MYSQL_DATABASE: lab
    ports:
      - "13306:3306"
    labels:
      nexus.project: lab
      nexus.service: mysql
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    labels:
      nexus.project: lab
      nexus.service: mongo
