package com.ivan.nexus.domain.activity;

public enum ActivityType {
    DEPLOYMENT_STARTED,
    DEPLOYMENT_SUCCESS,
    DEPLOYMENT_FAILED,
    CONTAINER_STARTED,
    CONTAINER_STOPPED,
    CONTAINER_RESTARTED,
    ERROR_DETECTED,
    ALERT_CREATED,
    ALERT_RESOLVED,
    HEALTH_CHECK_FAILED,
    GITHUB_CONNECTED,
    GITHUB_DISCONNECTED,
    SECURITY_SCAN_COMPLETED,
    DOMAIN_ADDED,
    DOMAIN_REMOVED,
    BACKUP_COMPLETED,
    BACKUP_FAILED
}
