package com.ivan.nexus.domain.shared;

public enum NexusErrorCode {
    PROJECT_NOT_FOUND,
    CONTAINER_NOT_FOUND,
    DEPLOYMENT_NOT_FOUND,
    ALERT_NOT_FOUND,
    MANIFEST_INVALID,
    MANIFEST_NOT_FOUND,
    OPERATION_NOT_ALLOWED,
    DEPLOYMENT_IN_PROGRESS,
    INVALID_TRANSITION,
    AUTH_INVALID,
    FORBIDDEN
}
