package com.ivan.nexus.domain.audit;

public enum AuditAction {
    LOGIN,
    DEPLOY,
    ROLLBACK,
    SERVICE_RESTART,
    CONFIG_CHANGE,
    ALERT_ACKNOWLEDGE,
    SECURITY_FINDING_ACKNOWLEDGE,
    DB_QUERY,
    DB_CELL_EDIT,
    GITHUB_CONNECT,
    GITHUB_DISCONNECT,
    TERMINAL_SESSION_START,
    TERMINAL_SESSION_END
}
